### ISSUE TITLE
Add CSS for tables

### ISSUE THREAD

**Issue by sdouche** [eliasson/liquorice#14]
Hi,
It would be cool to add a bunch of CSS codes to display nicely tables. For example:

```css
table {
width: 100%;
max-width: 100%;
border: 1px solid #aaa;
}

th, td {
padding: 2px 10px;
position: relative;
transition: all 300ms;
}

tr:nth-child(odd) td {
background: #f1f1f1;
}
```

Regards.
